version: 2.1
jobs:
  test:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      #- run: pod install
      - run: fastlane scan
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

  deploy:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - run:
          name: Deploy
          command: fastlane release_appstore

workflows:
  test_release:
    jobs:
      - test
      
